class CurrencyCountryMapper {
  static const Map<String, String> currencyToCountry = {
    'USD': 'US',
    'EUR': 'EU',
    'GBP': 'GB',
    'JPY': 'JP',
    'AUD': 'AU',
    'CAD': 'CA',
    'CHF': 'CH',
    'CNY': 'CN',
    'INR': 'IN',
    'BRL': 'BR',
    'ZAR': 'ZA',
    'MXN': 'MX',
    'RUB': 'RU',
    'KRW': 'KR',
    'SGD': 'SG',
    'HKD': 'HK',
    'NZD': 'NZ',
    'SEK': 'SE',
    'NOK': 'NO',
    'DKK': 'DK',
    'PLN': 'PL',
    'TRY': 'TR',
    'THB': 'TH',
    'IDR': 'ID',
    'MYR': 'MY',
    'PHP': 'PH',
    'AED': 'AE',
    'SAR': 'SA',
    'EGP': 'EG',
    'ILS': 'IL',
    'ARS': 'AR',
    'CLP': 'CL',
    'COP': 'CO',
    'PEN': 'PE',
    'VND': 'VN',
    'PKR': 'PK',
    'BGN': 'BG',
    'HRK': 'HR',
    'CZK': 'CZ',
    'HUF': 'HU',
    'RON': 'RO',
    'ISK': 'IS',
    'UAH': 'UA',
    'KZT': 'KZ',
    'NGN': 'NG',
    'KES': 'KE',
    'TZS': 'TZ',
    'UGX': 'UG',
    'ETB': 'ET',
    'GHS': 'GH',
    'XOF': 'SN',
    'XAF': 'CM',
    'MAD': 'MA',
    'DZD': 'DZ',
    'TND': 'TN',
    'LYD': 'LY',
    'SDG': 'SD',
    'IQD': 'IQ',
    'JOD': 'JO',
    'LBP': 'LB',
    'SYP': 'SY',
    'YER': 'YE',
    'OMR': 'OM',
    'KWD': 'KW',
    'BHD': 'BH',
    'QAR': 'QA',
    'AFN': 'AF',
    'IRR': 'IR',
    'AZN': 'AZ',
    'AMD': 'AM',
    'GEL': 'GE',
    'BYN': 'BY',
    'MDL': 'MD',
    'ALL': 'AL',
    'MKD': 'MK',
    'RSD': 'RS',
    'BAM': 'BA',
    'MNT': 'MN',
    'KGS': 'KG',
    'TJS': 'TJ',
    'TMT': 'TM',
    'UZS': 'UZ',
    'BDT': 'BD',
    'LKR': 'LK',
    'NPR': 'NP',
    'BTN': 'BT',
    'MMK': 'MM',
    'LAK': 'LA',
    'KHR': 'KH',
    'MOP': 'MO',
    'TWD': 'TW',
    'FJD': 'FJ',
    'PGK': 'PG',
    'SBD': 'SB',
    'VUV': 'VU',
    'XPF': 'PF',
    'WST': 'WS',
    'TOP': 'TO',
    'NIO': 'NI',
    'GTQ': 'GT',
    'BZD': 'BZ',
    'JMD': 'JM',
    'BBD': 'BB',
    'BMD': 'BM',
    'BSD': 'BS',
    'KYD': 'KY',
    'AWG': 'AW',
    'ANG': 'CW',
    'SRD': 'SR',
    'GYD': 'GY',
    'TTD': 'TT',
    'XCD': 'AG',
    'BND': 'BN',
    'MVR': 'MV',
    'SCR': 'SC',
    'DJF': 'DJ',
    'ERN': 'ER',
    'SOS': 'SO',
    'RWF': 'RW',
    'BIF': 'BI',
    'MWK': 'MW',
    'ZMW': 'ZM',
    'MZN': 'MZ',
    'AOA': 'AO',
    'SZL': 'SZ',
    'LSL': 'LS',
    'BWP': 'BW',
    'NAD': 'NA',
    'ZWL': 'ZW',
    'MGA': 'MG',
    'MUR': 'MU',
    'KMF': 'KM',
    'CDF': 'CD',
    'GNF': 'GN',
    'LRD': 'LR',
    'SLE': 'SL',
    'GMD': 'GM',
  };

  static String getCountryCode(String currencyCode) {
    // First try the mapping
    if (currencyToCountry.containsKey(currencyCode)) {
      return currencyToCountry[currencyCode]!;
    }
    
    // If currency code is 3 letters and starts with a country code pattern, use first 2 letters
    if (currencyCode.length >= 2) {
      final potentialCode = currencyCode.substring(0, 2).toUpperCase();
      // Validate it's likely a country code (2 uppercase letters)
      if (potentialCode.length == 2 && 
          potentialCode.codeUnits.every((c) => c >= 65 && c <= 90)) {
        return potentialCode;
      }
    }
    
    // Default fallback
    return 'US';
  }
}
